kind: pipeline
type: docker
name: default

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

steps:

  - name: Build java app
    image: docker:19.03.11-git
    commands:
      - docker build -t java-app -f Dockerfile .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: Verify
    image: java-app
    commands:
      - mvn verify