kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

concurrency:
  limit: 1

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

steps:

  - name: Build java app
    image: docker:19.03.11-git
    commands:
      - docker build -t java-app -f Dockerfile .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: Verify
    image: java-app
    pull: never
    commands:
      - mvn verify

  - name: Sonar scan
    image: java-app
    pull: never
    commands:
      - mvn sonar:sonar
        -Dsonar.projectKey=java-test
        -Dsonar.host.url=$(echo "https://2226-37-47-96-87.eu.ngrok.io")
        -Dsonar.login=13c4eeef2b79b1b87f1ddc55d0ed681ebed4e16a
        -Dsonar.pullrequest.provider=GitHub
        -Dsonar.pullrequest.github.repository=sneakydevec/java-repo
        -Dsonar.pullrequest.base=master
        -Dsonar.pullrequest.branch=sneakydevec-patch-1
        -Dsonar.pullrequest.key=1